Import("*")

env = env.Clone()
env.Append(CPPPATH = [Dir('includes')])
env.Append(CPPDEFINES = ['CONFIG_ARM'])

arch_arm_src = env.Localize([
	'entry.sx',
	'asmhelpers.sx',
	'bcopy.sx',
	'bzero.sx',
	'strchr.sx',
	'strcmp.sx',
	'strlen.sx',
	'strncmp.sx',
	'memcmp.sx',
	'arm.c',
	])
Export('arch_arm_src')

env.SConscript([
	'#plat-s5l8720/SConscript',
	'#plat-s5l8900/SConscript',
	'#plat-s5l8920/SConscript',
	'#plat-s5pc110a01/SConscript',
	], 'env')
